chan_id	CPU bus	BMC bus	Name
2	5	20	comex_voltmon1,comex_voltmon2
3	6	44	pdb_hotswap1,pdb_pwr_conv1,pdb_temp1
7	10	22	somdimm_temp1,somdimm_temp2
12	15	40	voltmon1,voltmon2,voltmon3,voltmon4,voltmon5,voltmon6,voltmon7,voltmon8,voltmon9,voltmon10,voltmon11,voltmon12,voltmon13,voltmon14,voltmon15,voltmon16
