#!/bin/sh
set -e
# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d hw-management-sync remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d hw-management-blacklist-generator remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d hw-management-fast-sysfs-monitor remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d hw-management-sysfs-monitor remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d hw-management-thermal-updater remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d hw-management-peripheral-updater remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d hw-management-tc remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d hw-management remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.6ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.6ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.6ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.6ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.6ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.6ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.6ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.6ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'hw-management-blacklist-generator.service' 'hw-management-fast-sysfs-monitor.service' 'hw-management-peripheral-updater.service' 'hw-management-sync.service' 'hw-management-sysfs-monitor.service' 'hw-management-tc.service' 'hw-management-thermal-updater.service' 'hw-management.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'hw-management-blacklist-generator.service' 'hw-management-fast-sysfs-monitor.service' 'hw-management-peripheral-updater.service' 'hw-management-sync.service' 'hw-management-sysfs-monitor.service' 'hw-management-tc.service' 'hw-management-thermal-updater.service' 'hw-management.service' >/dev/null || true
		deb-systemd-helper unmask 'hw-management-blacklist-generator.service' 'hw-management-fast-sysfs-monitor.service' 'hw-management-peripheral-updater.service' 'hw-management-sync.service' 'hw-management-sysfs-monitor.service' 'hw-management-tc.service' 'hw-management-thermal-updater.service' 'hw-management.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.6ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'hw-management-blacklist-generator.service' 'hw-management-fast-sysfs-monitor.service' 'hw-management-peripheral-updater.service' 'hw-management-sysfs-monitor.service' 'hw-management-tc.service' 'hw-management-thermal-updater.service' 'hw-management.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'hw-management-blacklist-generator.service' 'hw-management-fast-sysfs-monitor.service' 'hw-management-peripheral-updater.service' 'hw-management-sysfs-monitor.service' 'hw-management-tc.service' 'hw-management-thermal-updater.service' 'hw-management.service' >/dev/null || true
		deb-systemd-helper unmask 'hw-management-blacklist-generator.service' 'hw-management-fast-sysfs-monitor.service' 'hw-management-peripheral-updater.service' 'hw-management-sysfs-monitor.service' 'hw-management-tc.service' 'hw-management-thermal-updater.service' 'hw-management.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.6ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'hw-management-fast-sysfs-monitor.service' 'hw-management-peripheral-updater.service' 'hw-management-sysfs-monitor.service' 'hw-management-tc.service' 'hw-management-thermal-updater.service' 'hw-management.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'hw-management-fast-sysfs-monitor.service' 'hw-management-peripheral-updater.service' 'hw-management-sysfs-monitor.service' 'hw-management-tc.service' 'hw-management-thermal-updater.service' 'hw-management.service' >/dev/null || true
		deb-systemd-helper unmask 'hw-management-fast-sysfs-monitor.service' 'hw-management-peripheral-updater.service' 'hw-management-sysfs-monitor.service' 'hw-management-tc.service' 'hw-management-thermal-updater.service' 'hw-management.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.6ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'hw-management-peripheral-updater.service' 'hw-management-sysfs-monitor.service' 'hw-management-tc.service' 'hw-management-thermal-updater.service' 'hw-management.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'hw-management-peripheral-updater.service' 'hw-management-sysfs-monitor.service' 'hw-management-tc.service' 'hw-management-thermal-updater.service' 'hw-management.service' >/dev/null || true
		deb-systemd-helper unmask 'hw-management-peripheral-updater.service' 'hw-management-sysfs-monitor.service' 'hw-management-tc.service' 'hw-management-thermal-updater.service' 'hw-management.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.6ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'hw-management-peripheral-updater.service' 'hw-management-tc.service' 'hw-management-thermal-updater.service' 'hw-management.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'hw-management-peripheral-updater.service' 'hw-management-tc.service' 'hw-management-thermal-updater.service' 'hw-management.service' >/dev/null || true
		deb-systemd-helper unmask 'hw-management-peripheral-updater.service' 'hw-management-tc.service' 'hw-management-thermal-updater.service' 'hw-management.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.6ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'hw-management-peripheral-updater.service' 'hw-management-tc.service' 'hw-management.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'hw-management-peripheral-updater.service' 'hw-management-tc.service' 'hw-management.service' >/dev/null || true
		deb-systemd-helper unmask 'hw-management-peripheral-updater.service' 'hw-management-tc.service' 'hw-management.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.6ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'hw-management-tc.service' 'hw-management.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'hw-management-tc.service' 'hw-management.service' >/dev/null || true
		deb-systemd-helper unmask 'hw-management-tc.service' 'hw-management.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.6ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'hw-management.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'hw-management.service' >/dev/null || true
		deb-systemd-helper unmask 'hw-management.service' >/dev/null || true
	fi
fi
# End automatically added section
