#!/bin/bash
########################################################################
# Copyright (c) 2020 Mellanox Technologies. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the names of the copyright holders nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# Alternatively, this software may be distributed under the terms of the
# GNU General Public License ("GPL") version 2 as published by the Free
# Software Foundation.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

### BEGIN INIT INFO
# Provides: hw-management-tc
# Required-Start: $local_fs $remote_fs $syslog hw-management
# Required-Stop: $local_fs $remote_fs $syslog hw-management
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: <Thermal control for Mellanox systems>
# Description: <Thermal control for Mellanox systems>
### END INIT INFO
# Available options:
# start	- activate thermal control.
# stop	- deactivate thermal control.
#

. /lib/lsb/init-functions

EXECUTABLE=/usr/bin/hw_management_thermal_control.py
SERVICE=hw-management-tc
ACTION=$1
pid=/var/run/$SERVICE.pid

case $ACTION in
	start)
		start-stop-daemon --start --background --pidfile "$pid" --make-pidfile --startas $EXECUTABLE
	;;
	stop)
		start-stop-daemon --stop -s KILL --oknodo --pidfile "$pid" --remove-pidfile
	;;
	restart|try-restart|reload|force-reload)
		log_warning_msg message "$ACTION not supported"
		logger -t $SERVICE "$ACTION not supported"
	;;
	status)
		status_of_proc "$EXECUTABLE" $SERVICE
	;;
	*)
		echo "Usage: `basename $0` {start|stop|status}"
		exit 1
	;;
esac
