#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2020-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause

### BEGIN INIT INFO
# Provides: hw-management-tc
# Required-Start: $local_fs $remote_fs $syslog hw-management
# Required-Stop: $local_fs $remote_fs $syslog hw-management
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: <Thermal control for Mellanox systems>
# Description: <Thermal control for Mellanox systems>
### END INIT INFO
# Available options:
# start	- activate thermal control.
# stop	- deactivate thermal control.
#

. /lib/lsb/init-functions

EXECUTABLE=/usr/bin/hw_management_thermal_control.py
SERVICE=hw-management-tc
ACTION=$1
pid=/var/run/$SERVICE.pid

case $ACTION in
	start)
		start-stop-daemon --start --background --pidfile "$pid" --make-pidfile --startas $EXECUTABLE
	;;
	stop)
		start-stop-daemon --stop -s KILL --oknodo --pidfile "$pid" --remove-pidfile
	;;
	restart|try-restart|reload|force-reload)
		log_warning_msg message "$ACTION not supported"
		logger -t $SERVICE "$ACTION not supported"
	;;
	status)
		status_of_proc "$EXECUTABLE" $SERVICE
	;;
	*)
		echo "Usage: `basename $0` {start|stop|status}"
		exit 1
	;;
esac
