#!/bin/bash
# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2020-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause

### BEGIN INIT INFO
# Provides: hw-management-fast-sysfs-monitor
# Required-Start: $local_fs $remote_fs $syslog
# Required-Stop: $local_fs $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: <HW management Fast Lables Monitor>
# Description: <Monitors Fast hardware label changes in sysfs>
### END INIT INFO
# Available options:
# start	- start monitoring fast sysfs lables creation.
# stop	- stop monitoring fast sysfs lables creation.
#

. /lib/lsb/init-functions

EXECUTABLE=hw-management-fast-sysfs-monitor.sh
SERVICE=hw-management-fast-sysfs-monitor
ACTION=$1

__usage="
Usage: $(basename $0) [Options]

Options:
    start   Start hw-mngmt-fast-sysfs-monitor.
    stop    Stop hw-mngmt-fast-sysfs-monitor.
    restart
    force-reload    Performs hw-mngmt-fast-sysfs-monitor 'stop' and the 'start.
"

$EXECUTABLE $ACTION