#!/bin/sh
set -e

if ps -p 1 | grep -w init >/dev/null; then
	#initd detected
	if [ -x "/etc/init.d/hw-management" ]; then
		update-rc.d -f hw-management remove >/dev/null
		rm -f /etc/init.d/hw-management
	fi
else
	if systemctl list-unit-files | grep enabled | grep -Fq hw-management; then
		systemctl disable hw-management
		systemctl daemon-reload
	fi
fi
