#!/bin/sh
set -e

if ps -p 1 | grep -w init >/dev/null; then
	#initd detected
	if [ -x "/etc/init.d/hw-management" ]; then
		update-rc.d -f hw-management remove >/dev/null
		rm -f /etc/init.d/hw-management
	fi
fi
