#!/bin/sh
set -e

if ps -p 1 | grep -w init >/dev/null; then
	#initd detected
	cp -f /usr/bin/hw-management.sh /etc/init.d/hw-management
	if [ -x "/etc/init.d/hw-management" ]; then
		update-rc.d hw-management defaults >/dev/null
		invoke-rc.d hw-management start || exit $?
	fi
fi
