chan_id	CPU bus	BMC bus	Name
2	5	20	comex_voltmon1,comex_voltmon2
3	6	44	pdb_hotswap1,pdb_pwr_conv1,pdb_temp1
7	10	22	somdimm_temp1,somdimm_temp2
12	15	40	voltmon1,voltmon2,voltmon3,voltmon4,voltmon5,voltmon6,voltmon7,voltmon8,voltmon9,voltmon10,voltmon11,voltmon12,voltmon13,voltmon14,voltmon15,voltmon16
19	22	51	pdb_hotswap2,pdb_pwr_conv2,pdb_temp2
28	31	41	voltmon17,voltmon18,voltmon19,voltmon20,voltmon21,voltmon22,voltmon23,voltmon24,voltmon25,voltmon26,voltmon27,voltmon28,voltmon29,voltmon30,voltmon31,voltmon32
35	38	46	pdb_hotswap3,pdb_pwr_conv3,pdb_temp3
44	47	42	voltmon33,voltmon34,voltmon35,voltmon36,voltmon37,voltmon38,voltmon39,voltmon40,voltmon41,voltmon42,voltmon43,voltmon44,voltmon45,voltmon46,voltmon47,voltmon48
51	54	47	pdb_hotswap4,pdb_pwr_conv4,pdb_temp4
60	63	43	voltmon49,voltmon50,voltmon51,voltmon52,voltmon53,voltmon54,voltmon55,voltmon56,voltmon57,voltmon58,voltmon59,voltmon60,voltmon61,voltmon62,voltmon63,voltmon64
