chan_id	CPU bus	BMC bus	Name
2	5	17	comex_voltmon1,comex_voltmon2
3	6	21	pdb_hotswap1,pdb_pwr_conv1,pdb_temp1
4	7	22	pdb_hotswap2,pdb_pwr_conv2,pdb_temp2
7	10	19	somdimm_temp1,somdimm_temp2
12	15	24	voltmon1,voltmon2,voltmon3,voltmon4,voltmon5,voltmon6,voltmon7,voltmon8,voltmon19,voltmon20
13	16	25	voltmon9,voltmon10,voltmon11,voltmon12,voltmon13,voltmon14,voltmon15,voltmon16,voltmon17,voltmon18
21	24	26	swb_info
