chan_id	CPU bus	BMC bus	Name
2	5	17	comex_voltmon1,comex_voltmon2
3	6	21	pdb_hotswap1
4	7	22	voltmon1,voltmon2,voltmon3,pwr_conv1
7	10	19	somdimm_temp1,somdimm_temp2
10	13	27	swb_info
19	22	28	pdb_hotswap2
20	23	29	voltmon4,voltmon5,voltmon6
26	29	30	swb2_info
36	39	31	voltmon7,voltmon8,voltmon9,pwr_conv2
52	55	32	voltmon10,voltmon11,voltmon12
