chan_id	CPU bus	BMC bus	Name
2	6	25	comex_voltmon1,comex_voltmon2
3	7	26	pdb_hotswap1,pwr_conv1,pwr_conv2
4	8	27	voltmon1,voltmon2,voltmon3,voltmon4
10	14	37	swb_info
20	24	28	voltmon5,voltmon6,voltmon7,voltmon8
36	40	29	voltmon9,voltmon10,voltmon11,voltmon12
52	56	30	voltmon13,voltmon14,voltmon15,voltmon16
64	68	33	cable_cartridge1_eeprom
65	69	34	cable_cartridge2_eeprom
66	70	35	cable_cartridge3_eeprom
67	71	36	cable_cartridge4_eeprom
