name: Bump version
on:
  push:
    branches:
      - V.7.*_BR
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: sholeksandr/hw-mgmt@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |
          changelog=$(git log -1 --name-only --pretty="" | grep "debian/changelog")
          echo "$changelog"
          if [ -z "$changelog" ]; then exit 0; fi
          git config user.name github-actions
          git config user.email github-actions@github.com
          last_tag=$(git describe --tags | cut -c 3-)
          echo "$last_tag"
          sed -i "s/\(.*mlnx.\)[0-9.]*)\(.*\)/\1"$last_tag")\2/g" debian/changelog
          echo sed1
          sed -i "s/-- MellanoxBSP <system-sw-low-level@mellanox.com>.*$/-- MellanoxBSP <system-sw-low-level@mellanox.com> $(date -R)/g" debian/changelog
          echo sed2
          git add debian/changelog
          echo add
          git commit --amend --no-edit
          echo commit
          git push -f
          
