name: Bump version
on:
  push:
    branches:
      - V.7.*_BR
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |
       git fetch --tags
       git branch -r | grep -E ".*origin/V.7.[0-9]+.[0-9]+_BR$"
       commit=$(git rev-parse HEAD)
       current_branch=$(git rev-parse --abbrev-ref HEAD)
       #new=$(./.contrib/version_tag.py -b $current_branch)
       new="V.7.0020.2088"
       echo "new tag:" $new
       echo ::set-env name=new_tag::$new
       env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |
        changelog=$(git log -1 --name-only --pretty="" | grep "debian/changelog" || echo "changelog not updated in this commit")
        if [ -z "$changelog" ]; then exit 0; fi
        git config user.name github-actions
        git config user.email github-actions@github.com
        last_tag="${{ env.new_tag }}"
        sed -i "s/\(.*mlnx.\)[0-9.]*)\(.*\)/\1"$last_tag")\2/g" debian/changelog
        sed -i "s/-- MellanoxBSP <system-sw-low-level@mellanox.com>.*$/-- MellanoxBSP <system-sw-low-level@mellanox.com> $(date -R)/g" debian/changelog
        git add debian/changelog
        git commit --amend --no-edit
        git push -f
  
    - name: Tag commit
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "${{ env.new_tag }}"
