name: Bump version
on:
  push:
    branches:
      - V.7.*_BR
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |     
        current_branch=$(git rev-parse --abbrev-ref HEAD)
        new_tag=$(./.contrib/version_tag.py -b $current_branch)
        echo "Branch: $current_branch"
        echo Tag: "$new_tag"
        echo "new_tag=$new_tag" >> $GITHUB_ENV
        echo $(git log -1 --name-only)
        echo $(git status)
        changelog=$(git log -1 --name-only --pretty="" | grep "debian/changelog" || echo "changelog not updated in this commit")
        if [ ! -z "$changelog" ]; then exit 0; fi
        echo "Updating changelog..."
        sed -i "s/\(.*mlnx.\)V.[0-9.]*)\(.*\)/\1"$new_tag")\2/g" debian/changelog
        sed -i "s/-- MellanoxBSP <system-sw-low-level@mellanox.com>.*$/-- MellanoxBSP <system-sw-low-level@mellanox.com> $(date -R)/g" debian/changelog
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add debian/changelog
        git commit --amend --no-edit
        git push -f
        echo $(git log -1 --name-only)
        echo $(git status)
        
        
    - run: |    
        git tag $new_tag
        echo $(git log -1 --name-only)
        echo $(git status)
        git push --tags
        git push --tags
